package net.itechnicians.ncsco.entities;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CIVILIAN.
 */
public class Civilian {

    private Long id;
    /** Not-null value. */
    private String CivilianName;
    /** Not-null value. */
    private String CivilianAddress;
    private double CivilianBirthDate;
    private String CivilianDepartment;
    private String CivilianPosition;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Civilian() {
    }

    public Civilian(Long id) {
        this.id = id;
    }

    public Civilian(Long id, String CivilianName, String CivilianAddress, double CivilianBirthDate, String CivilianDepartment, String CivilianPosition) {
        this.id = id;
        this.CivilianName = CivilianName;
        this.CivilianAddress = CivilianAddress;
        this.CivilianBirthDate = CivilianBirthDate;
        this.CivilianDepartment = CivilianDepartment;
        this.CivilianPosition = CivilianPosition;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCivilianName() {
        return CivilianName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCivilianName(String CivilianName) {
        this.CivilianName = CivilianName;
    }

    /** Not-null value. */
    public String getCivilianAddress() {
        return CivilianAddress;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCivilianAddress(String CivilianAddress) {
        this.CivilianAddress = CivilianAddress;
    }

    public double getCivilianBirthDate() {
        return CivilianBirthDate;
    }

    public void setCivilianBirthDate(double CivilianBirthDate) {
        this.CivilianBirthDate = CivilianBirthDate;
    }

    public String getCivilianDepartment() {
        return CivilianDepartment;
    }

    public void setCivilianDepartment(String CivilianDepartment) {
        this.CivilianDepartment = CivilianDepartment;
    }

    public String getCivilianPosition() {
        return CivilianPosition;
    }

    public void setCivilianPosition(String CivilianPosition) {
        this.CivilianPosition = CivilianPosition;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
