package net.itechnicians.ncsco.entities;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig officerDaoConfig;
    private final DaoConfig otherRankDaoConfig;
    private final DaoConfig projectDaoConfig;
    private final DaoConfig civilianDaoConfig;

    private final OfficerDao officerDao;
    private final OtherRankDao otherRankDao;
    private final ProjectDao projectDao;
    private final CivilianDao civilianDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        officerDaoConfig = daoConfigMap.get(OfficerDao.class).clone();
        officerDaoConfig.initIdentityScope(type);

        otherRankDaoConfig = daoConfigMap.get(OtherRankDao.class).clone();
        otherRankDaoConfig.initIdentityScope(type);

        projectDaoConfig = daoConfigMap.get(ProjectDao.class).clone();
        projectDaoConfig.initIdentityScope(type);

        civilianDaoConfig = daoConfigMap.get(CivilianDao.class).clone();
        civilianDaoConfig.initIdentityScope(type);

        officerDao = new OfficerDao(officerDaoConfig, this);
        otherRankDao = new OtherRankDao(otherRankDaoConfig, this);
        projectDao = new ProjectDao(projectDaoConfig, this);
        civilianDao = new CivilianDao(civilianDaoConfig, this);

        registerDao(Officer.class, officerDao);
        registerDao(OtherRank.class, otherRankDao);
        registerDao(Project.class, projectDao);
        registerDao(Civilian.class, civilianDao);
    }
    
    public void clear() {
        officerDaoConfig.getIdentityScope().clear();
        otherRankDaoConfig.getIdentityScope().clear();
        projectDaoConfig.getIdentityScope().clear();
        civilianDaoConfig.getIdentityScope().clear();
    }

    public OfficerDao getOfficerDao() {
        return officerDao;
    }

    public OtherRankDao getOtherRankDao() {
        return otherRankDao;
    }

    public ProjectDao getProjectDao() {
        return projectDao;
    }

    public CivilianDao getCivilianDao() {
        return civilianDao;
    }

}
