package net.itechnicians.ncsco.entities;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table OFFICER.
 */
public class Officer {

    private Long id;
    /** Not-null value. */
    private String officerName;
    /** Not-null value. */
    private String officerAddress;
    private double officerBirthDate;
    /** Not-null value. */
    private String officerRank;
    private String officerDepartment;
    private String officerPosition;
    private long officerMilId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Officer() {
    }

    public Officer(Long id) {
        this.id = id;
    }

    public Officer(Long id, String officerName, String officerAddress, double officerBirthDate, String officerRank, String officerDepartment, String officerPosition, long officerMilId) {
        this.id = id;
        this.officerName = officerName;
        this.officerAddress = officerAddress;
        this.officerBirthDate = officerBirthDate;
        this.officerRank = officerRank;
        this.officerDepartment = officerDepartment;
        this.officerPosition = officerPosition;
        this.officerMilId = officerMilId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getOfficerName() {
        return officerName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOfficerName(String officerName) {
        this.officerName = officerName;
    }

    /** Not-null value. */
    public String getOfficerAddress() {
        return officerAddress;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOfficerAddress(String officerAddress) {
        this.officerAddress = officerAddress;
    }

    public double getOfficerBirthDate() {
        return officerBirthDate;
    }

    public void setOfficerBirthDate(double officerBirthDate) {
        this.officerBirthDate = officerBirthDate;
    }

    /** Not-null value. */
    public String getOfficerRank() {
        return officerRank;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOfficerRank(String officerRank) {
        this.officerRank = officerRank;
    }

    public String getOfficerDepartment() {
        return officerDepartment;
    }

    public void setOfficerDepartment(String officerDepartment) {
        this.officerDepartment = officerDepartment;
    }

    public String getOfficerPosition() {
        return officerPosition;
    }

    public void setOfficerPosition(String officerPosition) {
        this.officerPosition = officerPosition;
    }

    public long getOfficerMilId() {
        return officerMilId;
    }

    public void setOfficerMilId(long officerMilId) {
        this.officerMilId = officerMilId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
