package net.itechnicians.ncsco.entities;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table OTHER_RANK.
 */
public class OtherRank {

    private Long id;
    /** Not-null value. */
    private String OtherRankId;
    /** Not-null value. */
    private String OtherRankName;
    /** Not-null value. */
    private String OtherRankAddress;
    private double OtherRankBirthDate;
    /** Not-null value. */
    private String OtherRankRank;
    private String OtherRankDepartment;
    private String OtherRankPosition;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public OtherRank() {
    }

    public OtherRank(Long id) {
        this.id = id;
    }

    public OtherRank(Long id, String OtherRankId, String OtherRankName, String OtherRankAddress, double OtherRankBirthDate, String OtherRankRank, String OtherRankDepartment, String OtherRankPosition) {
        this.id = id;
        this.OtherRankId = OtherRankId;
        this.OtherRankName = OtherRankName;
        this.OtherRankAddress = OtherRankAddress;
        this.OtherRankBirthDate = OtherRankBirthDate;
        this.OtherRankRank = OtherRankRank;
        this.OtherRankDepartment = OtherRankDepartment;
        this.OtherRankPosition = OtherRankPosition;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getOtherRankId() {
        return OtherRankId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOtherRankId(String OtherRankId) {
        this.OtherRankId = OtherRankId;
    }

    /** Not-null value. */
    public String getOtherRankName() {
        return OtherRankName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOtherRankName(String OtherRankName) {
        this.OtherRankName = OtherRankName;
    }

    /** Not-null value. */
    public String getOtherRankAddress() {
        return OtherRankAddress;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOtherRankAddress(String OtherRankAddress) {
        this.OtherRankAddress = OtherRankAddress;
    }

    public double getOtherRankBirthDate() {
        return OtherRankBirthDate;
    }

    public void setOtherRankBirthDate(double OtherRankBirthDate) {
        this.OtherRankBirthDate = OtherRankBirthDate;
    }

    /** Not-null value. */
    public String getOtherRankRank() {
        return OtherRankRank;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOtherRankRank(String OtherRankRank) {
        this.OtherRankRank = OtherRankRank;
    }

    public String getOtherRankDepartment() {
        return OtherRankDepartment;
    }

    public void setOtherRankDepartment(String OtherRankDepartment) {
        this.OtherRankDepartment = OtherRankDepartment;
    }

    public String getOtherRankPosition() {
        return OtherRankPosition;
    }

    public void setOtherRankPosition(String OtherRankPosition) {
        this.OtherRankPosition = OtherRankPosition;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
